on: [ push ]

name: Build Nightly

env:
  LD_LIBRARY_PATH: "target/debug/deps:target/release/deps:${GITHUB_WORKSPACE}/target/debug/deps:${GITHUB_WORKSPACE}/target/release/deps:${HOME}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib:${LD_LIBRARY_PATH}"

jobs:
  check:
    name: Build Nightly for Linux x64
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt-get install -y libwayland-dev libxkbcommon-dev
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          lfs: true
          submodules: true

      - name: Install Stable Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Nightly in Release Mode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release